<?php

namespace App\Tests\Application\Person\Query;

use App\Application\Person\Query\FindInvitesQuery;
use App\Application\Shared\Query\QueryBusInterface;
use App\DataFixtures\InviteFixture;
use App\Domain\Shared\Criteria\Criteria;
use Exception;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class FindInvitesQueryHandlerTest extends KernelTestCase
{
    /**
     * @var object|null
     */
    private ?object $queryBus;

    /**
     * @var object|null
     */
    private ?object $fixtures;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->queryBus = static::getContainer()->get(QueryBusInterface::class);
        $databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();

        $this->fixtures = $databaseTool->loadFixtures([
            InviteFixture::class
        ])->getReferenceRepository();
    }

    public function test_find_invites_query() : void
    {
        $invitesSet[] = $this->fixtures->getReference('invite');
        $inviteQuery = new FindInvitesQuery(new Criteria([]));
        $invites = $this->queryBus->ask($inviteQuery);

        $result = [];
        foreach ($invites as $key => $invite) {
            $result[$key] = $invite;
        }

        self::assertEquals($invitesSet, $result);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->queryBus = null;
        $this->fixtures = null;
    }
}