<?php

namespace App\Tests\Application\Person\Query;

use App\Application\Person\Query\FindCountryQuery;
use App\Application\Shared\Query\QueryBusInterface;
use App\DataFixtures\CountryFixture;
use App\Domain\Person\Model\Country;
use Exception;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class FindCountryQueryTest extends KernelTestCase
{
    /**
     * @var object|null
     */
    private ?object $queryBus;

    /**
     * @var object|null
     */
    private ?object $fixtures;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->queryBus = static::getContainer()->get(QueryBusInterface::class);
        $databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();

        $this->fixtures = $databaseTool->loadFixtures([
            CountryFixture::class
        ])->getReferenceRepository();
    }

    public function test_find_country_query() : void
    {
        $countryId = $this->fixtures->getReference('country')->getCountryId();
        $countryQuery = new FindCountryQuery($countryId);
        /** @var Country $country */
        $country = $this->queryBus->ask($countryQuery);
        self::assertInstanceOf(Country::class, $country);
        self::assertEquals($countryId, $country->getCountryId());
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->queryBus = null;
        $this->fixtures = null;
    }
}