<?php

namespace App\Tests\Application\Person\Query;

use App\Application\Person\Query\FindPersonQuery;
use App\Application\Shared\Query\QueryBusInterface;
use App\DataFixtures\PersonFixture;
use App\Domain\Person\Model\Person;
use Exception;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class FindPersonQueryTest extends KernelTestCase
{
    /**
     * @var object|null
     */
    private ?object $queryBus;

    /**
     * @var object|null
     */
    private ?object $fixtures;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->queryBus = static::getContainer()->get(QueryBusInterface::class);
        $databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();

        $this->fixtures = $databaseTool->loadFixtures([
            PersonFixture::class
        ])->getReferenceRepository();
    }

    public function test_find_person_query() : void
    {
        $personId = $this->fixtures->getReference('person')->getPersonId();
        $personQuery = new FindPersonQuery($personId);
        /** @var Person $person */
        $person = $this->queryBus->ask($personQuery);
        self::assertInstanceOf(Person::class, $person);
        self::assertEquals($personId, $person->getPersonId());
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->queryBus = null;
        $this->fixtures = null;
    }
}