<?php

namespace App\Tests\Application\Person\Query;

use App\Application\Person\Query\FindCountriesQuery;
use App\Application\Shared\Query\QueryBusInterface;
use App\DataFixtures\CountryFixture;
use App\Domain\Shared\Criteria\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class FindCountriesQueryTest extends KernelTestCase
{
    /**
     * @var object|null
     */
    private ?object $queryBus;

    /**
     * @var object|null
     */
    private ?object $fixtures;


    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp();
        $this->queryBus = static::getContainer()->get(QueryBusInterface::class);
        $databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();

        $this->fixtures = $databaseTool->loadFixtures([
            CountryFixture::class
        ])->getReferenceRepository();
    }

    public function test_find_country_query() : void
    {
        $countriesSet[] = $this->fixtures->getReference('country');
        $countryQuery = new FindCountriesQuery(new Criteria([]));
        $countries = $this->queryBus->ask($countryQuery);

        $result = [];
        foreach ($countries as $key => $country) {
            $result[$key] = $country;
        }

        self::assertEquals($countriesSet, $result);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->queryBus = null;
        $this->fixtures = null;
    }
}