api_platform:
    mapping:
        paths: [ '%kernel.project_dir%/src/Infrastructure' ]
    defaults:
        normalization_context:
            skip_null_values: false
    patch_formats:
        json: [ 'application/merge-patch+json', 'application/json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        jsonld: [ 'application/ld+json' ]
    swagger:
        versions: [ 3 ]
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]
    exception_to_status:
        Symfony\Component\Security\Core\Exception\AccessDeniedException: 403
        App\Domain\Shared\Exception\AccessDeniedException: 403
        App\Domain\Shared\Exception\NotFoundException: 404
        App\Domain\Person\Exception\LoginNameAlreadyExistsException: 400
        App\Domain\Person\Exception\PublicAgreementDocumentsNotSignedException: 400
        App\Domain\Person\Exception\InvalidMnemonicException: 406
        App\Domain\Person\Exception\LockedPersonException: 423
