doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
            object_json: App\Infrastructure\Shared\Doctrine\Types\ObjectJsonType
            profile: App\Infrastructure\Shared\Doctrine\Types\ProfileType
            datetimetz_immutable_with_microseconds: App\Infrastructure\Shared\Doctrine\Types\DateTimeTzImmutableWithMicrosecondsType
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Domain'
                        prefix: 'App\Domain'
                        alias: Domain
                dql:
                    string_functions:
                        ILIKE: App\Infrastructure\Shared\Doctrine\Functions\Ilike

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
