framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN_ASYNC)%'
            sync: '%env(MESSENGER_TRANSPORT_DSN_SYNC)%'
            # failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Application\Shared\Query\QueryInterface': sync
            'App\Application\Shared\Command\CommandInterface': sync
            'App\Domain\Shared\Event\DomainEventInterface': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
