# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    email.from.email: '%env(MAIL_FROM_ADDRESS)%'
    email.from.name: '%env(MAIL_FROM_NAME)%'
    site.url: 'https://test.com'
    audit.auth.active_time: '5'

imports:
    - { resource: 'services/repositories.yaml' }
    - { resource: 'services/services.yaml' }
    - { resource: 'services/specifications.yaml' }
    - { resource: 'services/workflow.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # make classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/'
            - '../src/Infrastructure/Shared/Kernel.php'

    App\Infrastructure\Shared\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

    App\Infrastructure\Shared\ApiPlatform\EventListener\DeserializeListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 2 }
        # Autoconfiguration must be disabled to set a custom priority
        autoconfigure: false
        decorates: 'api_platform.listener.request.deserialize'
        arguments:
            $decorated: '@App\Infrastructure\Shared\ApiPlatform\EventListener\DeserializeListener.inner'

    # end communication gateways

    # redis

    Redis:
        # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
        class: Predis\Client
        arguments:
            - 'tcp://%env(REDIS_HOST)%:%env(int:REDIS_PORT)%'

            # uncomment the following if your Redis server requires a password
            # - auth:
            #     - '%env(REDIS_PASSWORD)%'

              # add more service definitions when explicit configuration is needed
            # please note that last definitions always *replace* previous ones
