<?php

namespace App\Domain\Shared\Enums;

enum BusinessRuleValidationErrorCodesEnum: int
{
    case TRANSFER_ACCOUNTS_WITH_DIFFERENT_CURRENCIES = 40;
    case WRONG_ACCOUNT_TYPE = 43;
    case ACTIVATION_MINIMAL_AMOUNT_ISSUE = 44;
    case SUCH_PROGRAM_ALREADY_EXISTS = 45;
    case CURRENT_CONTRACT_SUM_GREATER_THAN_SETUP_CONTRACT_SUM = 46;
    case PERSON_IS_NOT_ACTIVATED = 47;
    case CURRENT_CONTRACT_IS_ALREADY_ACTIVE = 48;
    case ROYALTY_IS_ALREADY_APPLIED = 51;
    case WRONG_ROYALTY_RECEIVER_ACCOUNT_TYPE = 52;
    case ACCOUNT_IS_NOT_ACTIVE = 60;
    case TRANSFER_IN_BOUND_OF_THE_SAME_ACCOUNTS = 70;
}
