<?php

namespace App\Tests\Domain\Person\Repository;

use App\Domain\Person\Enums\LoginTypeEnum;
use App\Domain\Person\Repository\CheckLoginByUserIdentifierExistsInterface;
use App\Domain\Person\ValueObject\Auth\UserIdentifier;
use App\Infrastructure\Person\Repository\Doctrine\LoginRepository;
use Exception;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class CheckLoginByUserIdentifierExistsInterfaceTest extends KernelTestCase
{
    /**
     * @var object|null
     */
    private ?object $repository;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp();
        /** @var LoginRepository repository */
        $this->repository = self::getContainer()->get(CheckLoginByUserIdentifierExistsInterface::class);
    }

    public function test_check_login_by_user_identifier() : void
    {
        $result = $this->repository->identifierExists(UserIdentifier::create(
            'test@gmail.com',
            LoginTypeEnum::LOGIN_TYPE_EMAIL->value
        ));

        self::assertFalse($result);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->repository = null;
    }
}